version: "3.8"
services:
  nextjs:
    build:
      context: ./
      dockerfile: Dockerfile

      target: base
    image: mynext:2
    networks:
      - webnetwork
networks:
  webnetwork:
    external: true
