version: "3.8"
services:
  nextjs:
    image: node:20
    hostname: mynextjs
    command: >
      sh -c "git clone https://github.com/activenode-edu/nextjs-only.git /nextjs && ls -al /nextjs && cd /nextjs && npm ci && npm run build && npm run start"
    networks:
      - webnetwork

networks:
  webnetwork:
    external: true
